import sapl_base.authorization_subscription_factory
from sapl_flask.src.sapl_flask.flask_authorization_subscription_factory import FlaskAuthorizationSubscriptionFactory

sapl_base.authorization_subscription_factory.auth_factory = FlaskAuthorizationSubscriptionFactory()



