# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapl_service.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'sapl_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sapl_service.proto\x12\x11io.sapl.api.proto\x1a\x10sapl_types.proto2\xce\x04\n\x1aPolicyDecisionPointService\x12\x62\n\x06\x44\x65\x63ide\x12,.io.sapl.api.proto.AuthorizationSubscription\x1a(.io.sapl.api.proto.AuthorizationDecision0\x01\x12\x64\n\nDecideOnce\x12,.io.sapl.api.proto.AuthorizationSubscription\x1a(.io.sapl.api.proto.AuthorizationDecision\x12x\n\x0bMultiDecide\x12\x31.io.sapl.api.proto.MultiAuthorizationSubscription\x1a\x34.io.sapl.api.proto.IdentifiableAuthorizationDecision0\x01\x12t\n\x0eMultiDecideAll\x12\x31.io.sapl.api.proto.MultiAuthorizationSubscription\x1a-.io.sapl.api.proto.MultiAuthorizationDecision0\x01\x12v\n\x12MultiDecideAllOnce\x12\x31.io.sapl.api.proto.MultiAuthorizationSubscription\x1a-.io.sapl.api.proto.MultiAuthorizationDecisionB(\n\x11io.sapl.api.protoB\x11SaplServiceProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapl_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021io.sapl.api.protoB\021SaplServiceProtosP\001'
  _globals['_POLICYDECISIONPOINTSERVICE']._serialized_start=60
  _globals['_POLICYDECISIONPOINTSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
