name: initial release on TestPyPI

on:
  push:
#tags:
      #- sapl_base_v*
      #- sapl_django_v*
      #- sapl_flask_v*
      #- sapl_tornado_v*


jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        packagename: [sapl_base, sapl_django, sapl_flask, sapl_tornado]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        #if: ${{ github.event_name == 'push' && startsWith(github.ref, format('refs/tags/{0}_v', matrix.packagename )) }}
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        #if: ${{ github.event_name == 'push' && startsWith(github.ref, format('refs/tags/{0}_v', matrix.packagename )) }}
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build ${{ matrix.packagename }}
        #if: ${{ github.event_name == 'push' && startsWith(github.ref, format('refs/tags/{0}_v', matrix.packagename )) }}
        run: python -m build ./${{ matrix.packagename }}
      - name: Publish ${{ matrix.packagename }}
        #if: ${{ github.event_name == 'push' && startsWith(github.ref, format('refs/tags/{0}_v', matrix.packagename )) }}
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          packages_dir: ./${{ matrix.packagename }}/dist
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/